name: Build and Deploy

on:
  push:
    branches:
      - experimenteel/samenwerken
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  pull-requests: write

env:
  PROJECT_ID: asses-k2n
  DEPLOYMENT_NAME: productie

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_build-images.yaml
    with:
      frontend-image: ghcr.io/minbzk/par-dpia-form/dev/frontend
      backend-image: ghcr.io/minbzk/par-dpia-form/dev/backend
      tag-latest: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Deploy to ZAD
        uses: RijksICTGilde/zad-actions/deploy@v4
        with:
          api-key: ${{ secrets.ZAD_API_KEY }}
          project-id: ${{ env.PROJECT_ID }}
          deployment-name: ${{ env.DEPLOYMENT_NAME }}
          wait-for-ready: 'true'
          components: >-
            [
              {"name": "frontend", "image": "${{ needs.build.outputs.frontend-image }}"},
              {"name": "api", "image": "${{ needs.build.outputs.backend-image }}"}
            ]
